language: node_js
node_js:
  - node

before_install:
  - npm install

env:
  global:
    secure: Na5clktjOy6ySjyFPeC1XkSKE7o39+FYy4aDTPcLt/gxvN03HZOaFzYRYfcxyNI/Akt95X1XxGEncs27+KzVGpxBMRPDAgZqziqQzzOV/33BJ+yYox+snuQF291RVEpjkuqaawjbLFgbjc2jbTOVrLG+JT1L40WuV5m0hDWFMDoP5H6vgjWamb6h6suMi1Pz/XLaJupHdeR4dogrxEeWd0JuvM+jKHf/s1MFOWcicRZynpqyFdWtjo9LTm8YoJGHtxhC8Chyqaz1wZKgzFuI2JpiVyrJOOJXexcwQ+vnwa2CWkTeaVwg60pdnMeSfIsXgFNNU9zBQv77p2S2VYQ6aQUASQYFgzzCvlmRH7k20dtMGobkT67Ofm6iWw6wRXE1bT+PNkNUSdInqZmCIHefiwC7puQOPXxwDaz5tOODIRxrSO4r5nEp3Twt+EOrepYZEaeHDLo9iEMnLM/p/9Mbg5GNrmb3bPka6WC+8CtZABypALQxz8MesV4NB4E1GLkPPgXUrURXt/1zPvHI/mv7+/yevfG7QG6qWvKtmKw99TgN6eUUN0KR5CEAF+2vx9jtnsvB1a9FqKZwjfMxNQg/JH2r7ECbbQKipBv4/Yn9wD1EY4Giv6lYeeopN5OH5Pc/4Rqe/q/muttTZlNALvZkBA3gl54cECssmJ+vIV6aBcI=

jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy
    if: "(branch = master) AND (NOT (type IN (pull_request)))"
    script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish
